spring.application.name=spring-soap-api-demo

logging.level.org.springframework.ws.server.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.server.MessageTracing.received=TRACE
logging.level.org.springframework.ws.soap.security=DEBUG